workflows:
  ios-release:
    name: iOS Release (App Store)
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        APP_STORE_APP_ID: "6759532654"
        BUNDLE_ID: "app.brickquote"
        TEAM_ID: "7DHC233L84"
      node: "22"
      xcode: latest
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "v*"
          include: true
    scripts:
      - name: Install npm dependencies
        script: npm ci

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR/ios/App
          LATEST=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID" 2>/dev/null || echo "0")
          echo "Latest TestFlight build: $LATEST"
          agvtool new-version -all $(($LATEST + 1))

      - name: Build IPA
        script: |
          # Use Xcode automatic signing with App Store Connect API key
          xcodebuild archive \
            -project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/build/ios/xcarchive/App.xcarchive" \
            -allowProvisioningUpdates \
            -authenticationKeyPath "$APP_STORE_CONNECT_PRIVATE_KEY" \
            -authenticationKeyID "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            -authenticationKeyIssuerID "$APP_STORE_CONNECT_ISSUER_ID" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CODE_SIGN_STYLE=Automatic

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/ios/xcarchive/App.xcarchive" \
            -exportPath "$CM_BUILD_DIR/build/ios/ipa" \
            -allowProvisioningUpdates \
            -authenticationKeyPath "$APP_STORE_CONNECT_PRIVATE_KEY" \
            -authenticationKeyID "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            -authenticationKeyIssuerID "$APP_STORE_CONNECT_ISSUER_ID" \
            -exportOptionsPlist /tmp/exportOptions.plist

          # exportOptions will be auto-generated, but create fallback
          if [ ! -f /tmp/exportOptions.plist ]; then
            cat > /tmp/exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>${TEAM_ID}</string>
          </dict>
          </plist>
          EOF
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - laloappsstudio@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - "Internal Testing"
        submit_to_app_store: false

  android-release:
    name: Android Release (Google Play)
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      android_signing:
        - brickquote_keystore
      vars:
        PACKAGE_NAME: "app.brickquote"
      node: "22"
      java: "17"
    scripts:
      - name: Install npm dependencies
        script: npm ci

      - name: Sync Capacitor Android
        script: npx cap sync android

      - name: Build Android AAB
        script: |
          cd android && ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - laloappsstudio@gmail.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
