workflows:
  ios-release:
    name: iOS Release (App Store)
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      groups:
        - ios
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        APP_STORE_APP_ID: "6759532654"
        BUNDLE_ID: "app.brickquote"
        TEAM_ID: "7DHC233L84"
      node: "22"
      xcode: latest
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "v*"
          include: true
    scripts:
      - name: Install npm dependencies
        script: npm ci

      - name: Sync Capacitor iOS + add Firebase SDK
        script: |
          npx cap sync ios

          # Add Firebase SDK to Package.swift (cap sync overwrites it)
          python3 << 'PYEOF'
          import re
          path = 'ios/App/CapApp-SPM/Package.swift'
          content = open(path).read()
          # Fix Windows backslashes from cap sync
          content = content.replace('\\\\', '/')
          # Add Firebase package dependency
          if 'firebase-ios-sdk' not in content:
              content = content.replace(
                  '.package(url: "https://github.com/ionic-team/capacitor-swift-pm.git"',
                  '.package(url: "https://github.com/firebase/firebase-ios-sdk.git", from: "11.0.0"),\n        .package(url: "https://github.com/ionic-team/capacitor-swift-pm.git"'
              )
              content = content.replace(
                  '.product(name: "Capacitor", package: "capacitor-swift-pm")',
                  '.product(name: "FirebaseMessaging", package: "firebase-ios-sdk"),\n                .product(name: "Capacitor", package: "capacitor-swift-pm")'
              )
          open(path, 'w').write(content)
          print("Firebase added to Package.swift")
          PYEOF
          cat ios/App/CapApp-SPM/Package.swift

      - name: Prepare API key
        script: |
          KEY_BODY=$(printf '%b' "$ASC_KEY_CONTENT" | tr -d '\r')
          if echo "$KEY_BODY" | head -1 | grep -q "BEGIN"; then
            echo "$KEY_BODY" > /tmp/AuthKey.p8
          else
            printf '%s\n%s\n%s\n' "-----BEGIN PRIVATE KEY-----" "$KEY_BODY" "-----END PRIVATE KEY-----" > /tmp/AuthKey.p8
          fi
          openssl pkey -in /tmp/AuthKey.p8 -noout && echo "Key is VALID" || { echo "Key is INVALID"; exit 1; }

      - name: Increment build number
        script: |
          export APP_STORE_CONNECT_PRIVATE_KEY="$(cat /tmp/AuthKey.p8)"
          cd $CM_BUILD_DIR/ios/App
          LATEST=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID" || echo "0")
          echo "Latest TestFlight build: $LATEST"
          agvtool new-version -all $(($LATEST + 1))

      - name: Set up signing and build IPA
        script: |
          export APP_STORE_CONNECT_PRIVATE_KEY="$(cat /tmp/AuthKey.p8)"

          # Generate fresh RSA key for new distribution certificate
          CERT_KEY=$(openssl genrsa 2048 2>/dev/null)

          # Revoke all existing distribution certificates to avoid Apple's limit
          # (each build creates a fresh key so old certs are unusable anyway)
          python3 << 'PYEOF'
          import subprocess, json
          try:
              for cert_type in ['DISTRIBUTION', 'IOS_DISTRIBUTION']:
                  r = subprocess.run(
                      ['app-store-connect', 'certificates', 'list',
                       '--type', cert_type, '--json'],
                      capture_output=True, text=True, timeout=30
                  )
                  if r.returncode == 0 and r.stdout.strip():
                      certs = json.loads(r.stdout)
                      for cert in certs:
                          cid = cert.get('id', '')
                          if cid:
                              print(f"Revoking certificate {cid}")
                              subprocess.run(
                                  ['app-store-connect', 'certificates', 'delete', cid],
                                  capture_output=True, timeout=30
                              )
          except Exception as e:
              print(f"Certificate cleanup: {e}")
          PYEOF

          # Fetch/create App Store distribution certificate + provisioning profile
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --certificate-key "$CERT_KEY"

          # Set up keychain and apply profiles to Xcode project
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

          # Build IPA (manual signing with fetched profiles)
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - laloappsstudio@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - "test"
        submit_to_app_store: false

  android-release:
    name: Android Release (Google Play)
    max_build_duration: 30
    instance_type: linux
    environment:
      groups:
        - android
      vars:
        PACKAGE_NAME: "app.brickquote"
      node: "22"
      java: "17"
    scripts:
      - name: Install npm dependencies
        script: npm ci

      - name: Sync Capacitor Android
        script: npx cap sync android

      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/brickquote-release.keystore

      - name: Build Android AAB
        script: |
          export KEYSTORE_PATH="$CM_BUILD_DIR/brickquote-release.keystore"
          export KEYSTORE_PASSWORD="$CM_KEYSTORE_PASSWORD"
          export KEY_ALIAS="$CM_KEY_ALIAS"
          export KEY_PASSWORD="$CM_KEY_PASSWORD"
          cd android && ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - laloappsstudio@gmail.com
        notify:
          success: true
          failure: true
