workflows:
  ios-release:
    name: iOS Release (App Store)
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        APP_STORE_APP_ID: "6759532654"
        BUNDLE_ID: "app.brickquote"
        TEAM_ID: "7DHC233L84"
      node: "22"
      xcode: latest
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "v*"
          include: true
    scripts:
      - name: Install npm dependencies
        script: npm ci

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR/ios/App
          LATEST=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID" 2>/dev/null || echo "0")
          echo "Latest TestFlight build: $LATEST"
          agvtool new-version -all $(($LATEST + 1))

      - name: Sign and build IPA
        script: |
          # Fetch signing files
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create --force
          keychain initialize
          keychain add-certificates

          # Extract provisioning profile UUID
          PROFILE_PATH=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" | head -1)
          echo "=== Profile path: $PROFILE_PATH ==="

          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c "Print UUID" /dev/stdin <<< "$(/usr/bin/security cms -D -i "$PROFILE_PATH")")
          echo "=== Profile UUID: $PROFILE_UUID ==="

          # Archive
          xcodebuild archive \
            -project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/build/ios/xcarchive/App.xcarchive" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PROVISIONING_PROFILE="$PROFILE_UUID" \
            PROVISIONING_PROFILE_SPECIFIER=

          # Export IPA
          cat > /tmp/exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>${TEAM_ID}</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${BUNDLE_ID}</key>
              <string>${PROFILE_UUID}</string>
            </dict>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/ios/xcarchive/App.xcarchive" \
            -exportPath "$CM_BUILD_DIR/build/ios/ipa" \
            -exportOptionsPlist /tmp/exportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - laloappsstudio@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - "Internal Testing"
        submit_to_app_store: false

  android-release:
    name: Android Release (Google Play)
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      android_signing:
        - brickquote_keystore
      vars:
        PACKAGE_NAME: "app.brickquote"
      node: "22"
      java: "17"
    scripts:
      - name: Install npm dependencies
        script: npm ci

      - name: Sync Capacitor Android
        script: npx cap sync android

      - name: Build Android AAB
        script: |
          cd android && ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - laloappsstudio@gmail.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
