workflows:
  ios-release:
    name: iOS Release (App Store)
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        APP_STORE_APP_ID: "6759532654"
        BUNDLE_ID: "app.brickquote"
        TEAM_ID: "7DHC233L84"
      node: "22"
      xcode: latest
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "v*"
          include: true
    scripts:
      - name: Install npm dependencies
        script: npm ci

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR/ios/App
          LATEST=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID" 2>/dev/null || echo "0")
          echo "Latest TestFlight build: $LATEST"
          agvtool new-version -all $(($LATEST + 1))

      - name: Build IPA
        script: |
          # Write App Store Connect API key to file
          printf '%s\n' "$APP_STORE_CONNECT_PRIVATE_KEY" > /tmp/AuthKey.p8
          chmod 600 /tmp/AuthKey.p8

          # Archive with automatic signing
          xcodebuild archive \
            -project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/build/ios/xcarchive/App.xcarchive" \
            -allowProvisioningUpdates \
            -authenticationKeyPath /tmp/AuthKey.p8 \
            -authenticationKeyID "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            -authenticationKeyIssuerID "$APP_STORE_CONNECT_ISSUER_ID" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CODE_SIGN_STYLE=Automatic

          # Create export options
          /usr/libexec/PlistBuddy -c "Add :method string app-store" /tmp/exportOptions.plist
          /usr/libexec/PlistBuddy -c "Add :signingStyle string automatic" /tmp/exportOptions.plist
          /usr/libexec/PlistBuddy -c "Add :teamID string 7DHC233L84" /tmp/exportOptions.plist

          # Export IPA
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/ios/xcarchive/App.xcarchive" \
            -exportPath "$CM_BUILD_DIR/build/ios/ipa" \
            -allowProvisioningUpdates \
            -authenticationKeyPath /tmp/AuthKey.p8 \
            -authenticationKeyID "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            -authenticationKeyIssuerID "$APP_STORE_CONNECT_ISSUER_ID" \
            -exportOptionsPlist /tmp/exportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - laloappsstudio@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - "Internal Testing"
        submit_to_app_store: false

  android-release:
    name: Android Release (Google Play)
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      android_signing:
        - brickquote_keystore
      vars:
        PACKAGE_NAME: "app.brickquote"
      node: "22"
      java: "17"
    scripts:
      - name: Install npm dependencies
        script: npm ci

      - name: Sync Capacitor Android
        script: npx cap sync android

      - name: Build Android AAB
        script: |
          cd android && ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - laloappsstudio@gmail.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
